project_id = "pvuxlnllahyfhqhcmpwk"

[functions.chat]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.generate-video]
verify_jwt = false

[functions.run-code]
verify_jwt = false
